import React, { useRef } from "react";
import {
  FileText,
  Printer,
  Download,
  ShieldCheck,
  CheckCircle2,
  Calendar,
  UserCheck,
  MapPin,
  Camera,
  Film,
  Award,
} from "lucide-react";
import { Case, Evidence, CCTVDevice, AnalysisEvent, ChainOfCustodyRecord } from "../types";

interface ReportGeneratorViewProps {
  activeCase: Case;
  evidenceList: Evidence[];
  devices: CCTVDevice[];
  events: AnalysisEvent[];
  records: ChainOfCustodyRecord[];
}

export const ReportGeneratorView: React.FC<ReportGeneratorViewProps> = ({
  activeCase,
  evidenceList = [],
  devices = [],
  events = [],
  records = [],
}) => {
  const printRef = useRef<HTMLDivElement>(null);

  const safeCase: Case = activeCase || {
    case_id: "CASE-2026-001",
    case_number: "CR-99201",
    case_name: "Active Investigation",
    description: "Digital forensic video evidence analysis",
    created_at: new Date().toISOString().substring(0, 10),
    investigator: "Insp. David Vance",
    status: "Active",
    priority: "High",
    incident_location: "Sector Downtown Area",
    incident_lat: 40.7128,
    incident_lng: -74.006,
  };

  const safeEvidence = Array.isArray(evidenceList) ? evidenceList : [];
  const safeDevices = Array.isArray(devices) ? devices : [];
  const safeEvents = Array.isArray(events) ? events : [];
  const safeRecords = Array.isArray(records) ? records : [];

  const handlePrint = () => {
    window.print();
  };

  const handleExportJson = () => {
    const reportData = {
      case: safeCase,
      devices: safeDevices,
      evidence: safeEvidence,
      timeline_events: safeEvents,
      chain_of_custody: safeRecords,
      generated_at: new Date().toISOString(),
      standards: "NIST SP 800-86 / ISO/IEC 27037",
    };
    const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `FORENSIC_EXAMINATION_REPORT_${safeCase.case_number || "EXPORT"}.json`;
    a.click();
  };

  const handleDownloadServerPdf = async () => {
    try {
      const res = await fetch("/api/reports/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ case_id: safeCase.case_id }),
      });
      const data = await res.json();
      if (data?.pdf_download_url) {
        window.open(data.pdf_download_url, "_blank");
      } else {
        window.print();
      }
    } catch (err) {
      window.print();
    }
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-slate-900 border border-slate-800 p-5 rounded-xl print:hidden">
        <div>
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-emerald-400" />
            <h2 className="text-lg font-bold text-white tracking-tight">
              Judicial Forensic Examination Report
            </h2>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Standardized technical document adhering to ISO/IEC 27037 & NIST SP 800-86 digital evidence presentation guidelines.
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <button
            onClick={handleExportJson}
            className="flex items-center gap-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold px-3.5 py-2 rounded-lg border border-slate-700 transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            Export Raw JSON
          </button>
          <button
            onClick={handleDownloadServerPdf}
            className="flex items-center gap-1.5 bg-purple-600 hover:bg-purple-500 text-white text-xs font-semibold px-3.5 py-2 rounded-lg shadow-sm transition-colors cursor-pointer"
            title="Download official PDF generated by FastAPI backend"
          >
            <Award className="w-3.5 h-3.5" />
            Official PDF (Backend)
          </button>
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold px-4 py-2 rounded-lg shadow-sm transition-colors"
          >
            <Printer className="w-4 h-4" />
            Print / Save to PDF
          </button>
        </div>
      </div>

      {/* Printable Report Document (Styled for white paper when printing, dark inside UI) */}
      <div
        ref={printRef}
        className="bg-white text-slate-900 p-8 sm:p-12 rounded-xl shadow-2xl border border-slate-200 space-y-8 font-sans max-w-5xl mx-auto print:border-none print:shadow-none print:p-0 print:m-0"
      >
        {/* Document Header & Seal */}
        <div className="border-b-2 border-slate-900 pb-6 flex flex-col sm:flex-row sm:items-start justify-between gap-6">
          <div className="flex items-start gap-4">
            <div className="h-16 w-16 bg-slate-900 text-emerald-400 rounded-xl flex items-center justify-center p-3 shrink-0">
              <ShieldCheck className="w-full h-full" />
            </div>
            <div>
              <span className="text-[11px] font-mono font-bold tracking-widest text-slate-600 uppercase block">
                OFFICIAL LAW ENFORCEMENT FORENSIC DIVISION
              </span>
              <h1 className="text-2xl font-black text-slate-950 tracking-tight mt-0.5">
                DIGITAL VIDEO FORENSIC EXAMINATION REPORT
              </h1>
              <span className="text-xs text-slate-700 mt-1 block">
                Evidence Integrity & Chronological Incident Analysis
              </span>
            </div>
          </div>

          <div className="text-right font-mono text-xs text-slate-700 space-y-1">
            <div>
              <span className="text-slate-500">REPORT NO:</span>{" "}
              <strong className="text-slate-950">REP-{safeCase.case_number}</strong>
            </div>
            <div>
              <span className="text-slate-500">DATE:</span>{" "}
              <strong className="text-slate-950">
                {new Date().toISOString().substring(0, 10)}
              </strong>
            </div>
            <div>
              <span className="text-slate-500">CLASSIFICATION:</span>{" "}
              <strong className="text-rose-700">CONFIDENTIAL // LAW ENFORCEMENT SENSITIVE</strong>
            </div>
          </div>
        </div>

        {/* Section 1: Case Details */}
        <div className="space-y-3">
          <h2 className="text-xs font-bold text-slate-950 uppercase tracking-wider border-b border-slate-300 pb-1">
            Section 1: Case Identification
          </h2>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 bg-slate-50 p-4 rounded-lg border border-slate-200 text-xs">
            <div>
              <span className="text-slate-500 block text-[11px]">Case Number</span>
              <strong className="text-slate-900 font-mono text-sm">{safeCase.case_number}</strong>
            </div>
            <div>
              <span className="text-slate-500 block text-[11px]">Case Name</span>
              <strong className="text-slate-900">{safeCase.case_name}</strong>
            </div>
            <div>
              <span className="text-slate-500 block text-[11px]">Primary Investigator</span>
              <strong className="text-slate-900">{safeCase.investigator}</strong>
            </div>
            <div>
              <span className="text-slate-500 block text-[11px]">Incident Location</span>
              <strong className="text-slate-900">{safeCase.incident_location}</strong>
            </div>
          </div>
          <p className="text-xs text-slate-700 italic px-1">
            Overview: {safeCase.description || "Forensic acquisition of CCTV surveillance streams relating to the reported incident corridor."}
          </p>
        </div>

        {/* Section 2: Originating CCTV Devices */}
        <div className="space-y-3">
          <h2 className="text-xs font-bold text-slate-950 uppercase tracking-wider border-b border-slate-300 pb-1">
            Section 2: Surveillance Device Registry
          </h2>
          <table className="w-full text-left text-xs border border-slate-200">
            <thead className="bg-slate-100 text-slate-700 font-semibold border-b border-slate-200">
              <tr>
                <th className="p-2.5">CCTV ID</th>
                <th className="p-2.5">Camera Name</th>
                <th className="p-2.5">Vendor / Model</th>
                <th className="p-2.5">IP Address / Ch</th>
                <th className="p-2.5">GIS Location</th>
                <th className="p-2.5">Coverage</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 text-slate-800">
              {safeDevices.map((d) => (
                <tr key={d.cctv_id}>
                  <td className="p-2.5 font-mono font-bold">{d.cctv_id}</td>
                  <td className="p-2.5">{d.name}</td>
                  <td className="p-2.5">{d.vendor} ({d.model})</td>
                  <td className="p-2.5 font-mono">{d.ip_address} (Ch {d.channel})</td>
                  <td className="p-2.5">{d.location}</td>
                  <td className="p-2.5">{d.direction}° ({d.coverage_radius}m)</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Section 3: Evidence Files & Cryptographic SHA-256 Hashes */}
        <div className="space-y-3">
          <h2 className="text-xs font-bold text-slate-950 uppercase tracking-wider border-b border-slate-300 pb-1">
            Section 3: Digital Evidence Seizure & SHA-256 Hash Integrity
          </h2>
          <table className="w-full text-left text-xs border border-slate-200">
            <thead className="bg-slate-100 text-slate-700 font-semibold border-b border-slate-200">
              <tr>
                <th className="p-2.5">Evidence ID</th>
                <th className="p-2.5">File Name & Size</th>
                <th className="p-2.5">Duration / FPS</th>
                <th className="p-2.5">Cryptographic SHA-256 Digest (NIST FIPS 180-4)</th>
                <th className="p-2.5">Integrity Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 text-slate-800">
              {safeEvidence.map((ev) => (
                <tr key={ev.evidence_id}>
                  <td className="p-2.5 font-mono font-bold text-slate-950">{ev.evidence_id}</td>
                  <td className="p-2.5">
                    <div className="font-semibold">{ev.file_name}</div>
                    <span className="text-[10px] text-slate-500">{ev.file_size}</span>
                  </td>
                  <td className="p-2.5 font-mono">
                    <div>{ev.metadata?.duration || "N/A"}</div>
                    <span className="text-[10px] text-slate-500">{ev.metadata?.fps ?? 30} FPS</span>
                  </td>
                  <td className="p-2.5 font-mono text-[10px] break-all select-all text-slate-900 max-w-xs">
                    {ev.sha256_hash}
                  </td>
                  <td className="p-2.5">
                    <span className="inline-flex items-center gap-1 font-bold text-emerald-700">
                      <CheckCircle2 className="w-3.5 h-3.5" />
                      VERIFIED MATCH
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Section 4: Chronological Timeline Analysis */}
        <div className="space-y-3">
          <h2 className="text-xs font-bold text-slate-950 uppercase tracking-wider border-b border-slate-300 pb-1">
            Section 4: Chronological Timeline & Key Observations
          </h2>
          <table className="w-full text-left text-xs border border-slate-200">
            <thead className="bg-slate-100 text-slate-700 font-semibold border-b border-slate-200">
              <tr>
                <th className="p-2.5">Timecode</th>
                <th className="p-2.5">Evidence Ref</th>
                <th className="p-2.5">Category</th>
                <th className="p-2.5">Observation / Forensic Finding</th>
                <th className="p-2.5">Confidence</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 text-slate-800">
              {safeEvents.map((evt) => (
                <tr key={evt.id}>
                  <td className="p-2.5 font-mono font-bold text-slate-950">{evt.timecode}</td>
                  <td className="p-2.5 font-mono">{evt.evidence_id}</td>
                  <td className="p-2.5 uppercase text-[10px] font-semibold">{evt.category}</td>
                  <td className="p-2.5">
                    <strong className="text-slate-950 block">{evt.label}</strong>
                    <span className="text-[11px] text-slate-600">{evt.notes}</span>
                  </td>
                  <td className="p-2.5 font-mono">{((evt.confidence || 0) * 100).toFixed(0)}%</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Section 5: Chain of Custody Audit Log */}
        <div className="space-y-3">
          <h2 className="text-xs font-bold text-slate-950 uppercase tracking-wider border-b border-slate-300 pb-1">
            Section 5: Chain of Custody Audit Log
          </h2>
          <table className="w-full text-left text-xs border border-slate-200">
            <thead className="bg-slate-100 text-slate-700 font-semibold border-b border-slate-200">
              <tr>
                <th className="p-2.5">Timestamp (UTC)</th>
                <th className="p-2.5">Authorized Agent</th>
                <th className="p-2.5">Evidence Item</th>
                <th className="p-2.5">Action Taken</th>
                <th className="p-2.5">Audit Notes</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 text-slate-800">
              {safeRecords.map((r) => (
                <tr key={r.record_id}>
                  <td className="p-2.5 font-mono text-[11px]">{r.timestamp}</td>
                  <td className="p-2.5 font-medium">{r.user}</td>
                  <td className="p-2.5 font-mono">{r.evidence_id}</td>
                  <td className="p-2.5 font-semibold">{r.action}</td>
                  <td className="p-2.5 text-slate-600">{r.notes}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Section 6: Certification & Investigator Signature */}
        <div className="pt-6 border-t-2 border-slate-900 space-y-6">
          <p className="text-xs text-slate-700 leading-relaxed">
            I hereby certify under penalty of perjury that the digital video evidence described above has been seized, examined, and maintained in strict accordance with the documented chain of custody and digital forensics best practices. The cryptographic SHA-256 hashes confirm bit-for-bit authenticity with no post-acquisition alterations.
          </p>

          <div className="grid grid-cols-2 gap-8 pt-4">
            <div>
              <div className="border-b border-slate-950 h-10 flex items-end font-serif italic text-base text-slate-900">
                Insp. David Vance
              </div>
              <span className="text-[11px] text-slate-600 uppercase tracking-wider block mt-1">
                Lead Forensic Video Examiner (Badge #V-4921)
              </span>
            </div>

            <div>
              <div className="border-b border-slate-950 h-10 flex items-end font-mono text-sm text-slate-900">
                {new Date().toISOString().substring(0, 10)}
              </div>
              <span className="text-[11px] text-slate-600 uppercase tracking-wider block mt-1">
                Date Certified
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
